name: LHCI-PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  lhci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.16.1 ]
    steps:
      - name: Working dir check
        run: echo $(pwd)
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Run Build
        run: npm run build
      - name: Run Custom Action
        id: run_custom_action
        uses: seungjaey/lhci-custom-action@v0.0.8
        with:
          INPUT_URL_PREFIX: http://localhost:3000
          INPUT_URL_LIST: |
            [상품상세] 싱글 콘텐츠__SEP__/
            [상품상세] 멀티 콘텐츠__SEP__/about
            [상품상세] 옵션형 콘텐츠__SEP__/faq
          INPUT_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
