name: LHCI-PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  lhci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.16.1 ]
    steps:
      - name: Working dir check
        run: echo $(pwd)
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up npm
        run: npm ci
      - name: Run Build
        run: npm run build
      - name: Run Lighthouse Box
        uses: abordage/lighthouse-box@1.0.2
        with:
          INPUT_GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INPUT_GIST_ID: 183e93e101576aaf73381ea9d2f6c7ef
          INPUT_TEST_URL: https://hamtolchu.dev/
