name: LHCI-PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  lhci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.16.1 ]
    steps:
      - name: Working dir check
        run: echo $(pwd)
      - name: Meaningless
        run: echo 1
      - name: Check Chrome
        run: echo $CHROME_PATH
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install Packages
        run: npm install
      - name: Create lighthouserc.json per Formfactor
        id: create-lighthouse-configs
        uses: seungjaey/create-lighthouse-ci-config-files@v0.0.beta-0.1
        with:
          URL_PREFIX: http://localhost:3000
          URL_LIST: |
            홈__SEP__/
            포스트__SEP__/posts
      - name: Check Result - Mobile
        run: echo "${{ steps.create-lighthouse-configs.outputs.MOBILE_CONFIG_FILE_NAME }}"
      - name: Check Result - Desktop
        run: echo "${{ steps.create-lighthouse-configs.outputs.DESKTOP_CONFIG_FILE_NAME }}"
      - name: Check File - Mobile
        run: echo $(cat ${{ steps.create-lighthouse-configs.outputs.MOBILE_CONFIG_FILE_NAME }})
      - name: Check File - Desktop
        run: echo $(cat ${{ steps.create-lighthouse-configs.outputs.DESKTOP_CONFIG_FILE_NAME }})
