name: LHCI-PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  lhci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.16.1 ]
    steps:
      - name: Working dir check
        run: echo $(pwd)
      - name: Check Chrome
        run: echo $CHROME_PATH
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set up pnpm
        uses: pnpm/action-setup@v2.2.2
        id: pnpm-install
        with:
          version: 7.5.0
          run_install: false
      - name: Install dependencies
        run: pnpm install
      - name: Run Build
        run: pnpm run build:dev
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v9
        with:
          urls: |
            https://hamtolchu.dev/
            https://hamtolchu.dev/photos
          budgetPath: ./budget.json # test performance budgets
          uploadArtifacts: true # save results as an action artifacts
          temporaryPublicStorage: true # upload lighthouse report to the temporary storage
